[project]
name = "sensitivity-analysis"
version = "0.1.0"
description = "Sensitivity analysis for RLC DC grid parameters"
authors = [
    {name = "geraldck",email = "geraldck@kth.se"}
]
requires-python = ">=3.12"
dependencies = [
    "salib (>=1.5.2,<2.0.0)",
    "scikit-learn (>=1.9.0,<2.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "pandas (>=3.0.3,<4.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
