step_voltage_ref:
  model: ../../mmc_sim/tests/step_voltage_reference/pscad_model/MMC_step_voltage_reference.pscx
  name: MMC_step_voltage_reference
  mva: 1200
  fn: 50
  ref_power: 900
  step_voltage: 652.8
  reference_voltage: 640.
  SCR: 10
  XR: 10
  ac_voltage: 400.
  step_time: 3.
  time_duration: 6
  sample_step: 100
  time_step: 10
  components:
    mmc_id: 171519397
    ac_grid_id: 13902648
  results:
    file_name: step_u_ref_response
    result_file: ../../mmc_sim/tests/step_voltage_reference/pscad_model/MMC_step_voltage_reference.gf46
    save_path: ../output/simulation_results/step_up_voltage_ref_response

sensitivity_analysis:
  output:
    sample_data: ../output/sample_data/sample_data.csv
    sample_data_dir: ../output/sample_data
    sim_data: ../output/sample_data/SA_step_up_u_ref_response_summary.csv